name: ROCm Build
on: [push, pull_request]

jobs:
  build-rocm:
    runs-on: ubuntu-latest
    container:
      image: rocm/dev-ubuntu-22.04:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update
          apt install -y wget tar
          wget -qO- "https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C /usr/local

      - name: Build with CMake
        run: |
          cmake -B build -DODYSSEY_BACKEND=HIP -DCMAKE_BUILD_TYPE=Release
          cmake --build build
